---
outdir: 'SC8SCAN_deepsets_8bit_28const'
data_hyperparams:

  root: "/work/aserinke/l1-jet-id/data/test"

  nconst: 28

  pdg_order: [22, -11, 11, -13, 13, 130, -211, 211]

  norm: "standard"

  kfolds: 5

  seed: 42

  datasets:
    bkg:
      - "/work/aserinke/SC8_Data/SingleNeutrino/1.root"
      - "/work/aserinke/SC8_Data/SingleNeutrino/2.root"
      - "/work/aserinke/SC8_Data/SingleNeutrino/3.root"
    sig:
      - "/work/aserinke/SC8_Data/lightHbb/lightHbb_M20to80_Pt50to200.root"

  test_size: 0.2
  random_state: 42

model_type: "qinvariant"
model_hyperparams:
  phi_layers: [64]
  rho_layers: [32, 4]
  activ: "relu"
  aggreg: "mean"
  output_dim: 2
  nbits: 8

compilation_hyperparams:
  optimizer: "adam"
  optimizer_hps:
    learning_rate: 0.0029
  optimizer_callbacks:
    early_stopping:
      monitor: "val_accuracy"
      patience: 20
    lr_decay:
      monitor: "val_accuracy"
      factor: 0.8
      patience: 10
      min_lr: 0.0001

  loss: "softmax_with_crossentropy"
  metrics: ["accuracy"]
  early_stopping: 20

training_hyperparams:
  batch_size: 256
  epochs: 1000
  shuffle: True
  verbose: 2
